[package]
name = "httpwm"
version = "0.1.0"
authors = ["Icelk <main@icelk.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "httpwmd"
path = "src/bin/main.rs"
doc = true
required-features = ["bin"]

[lib]
name = "httpwm"

[dependencies]
rppal = "0.11.3"
kvarn = { path = "kvarn", default-features = false, optional = true, features = ["no-cache"] }
kvarn_extensions = { path = "kvarn/kvarn_extensions", default-features = false, optional = true }
chrono = "0.4.19"
serde = { version = "1.0.123", optional = true, features = ["derive"] }
serde_json = { version = "1.0.64", optional = true }

[features]
default = ["bin"]
bin = ["web"]
web = ["kvarn", "kvarn_extensions", "json"]
json = ["serde", "serde_json"]
test = []
