[package]
name = "pwm_dev"
version = "0.1.0"
authors = ["Icelk <main@icelk.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pwm_http"
path = "src/bin/main.rs"
doc = false
required-features = ["bin"]

[lib]
name = "pwm_dev"

[dependencies]
rppal = "0.11.3"
kvarn = { path = "kvarn", no-default-features = true, optional = true }
chrono = "0.4.19"

[features]
default = ["bin"]
bin = ["kvarn"]
